-- Platform-level admin role on the user table. This is the GLOBAL role that
-- gates the internal admin dashboard (admin.clankersupport.com) — cross-tenant
-- metrics (signups, revenue, subscriptions). It is distinct from the
-- workspace-scoped `member.role` (owner|admin|agent), which only governs
-- permissions WITHIN a single workspace.
--
-- Additive ADD COLUMN with a NOT NULL DEFAULT, matching the 0004 idiom: every
-- existing user backfills to the least-privileged 'user'. Ploy's ledger applies
-- each migration file once, in filename order.
--
-- Preview-safety (migrate-before-serve, mirroring 0014/0015): this column is
-- ADDED here but deliberately NOT declared on the Drizzle `user` table in
-- schema.ts. Better Auth's adapter loads the session user with an unprojected
-- `select().from(user)` on every request, so declaring the column in schema.ts
-- would 500 all auth on a preview DB that skipped this migration. The /admin/*
-- routes read `role` via an explicit `sql` projection (fault-tolerant), so no
-- code path names the column unless it exists. Admin access also falls back to
-- the ADMIN_EMAILS env allowlist (verified emails only).
ALTER TABLE `user` ADD COLUMN `role` text DEFAULT 'user' NOT NULL;
