// Originally generated by `ploy types`, now MAINTAINED BY HAND.
//
// Ploy dropped the `env:` block from ploy.yaml (env vars are no longer
// declared — they come from the Ploy project settings at runtime and a local
// .env in dev). `ploy types` derives `vars` from that block, so re-running it
// here would emit an EMPTY `vars` and break the ~66 `env.vars.*` reads across
// src/ at typecheck time. Don't regenerate this file — add new variables to
// the `vars` block below by hand (and to apps/api/.env.example), keeping
// optional (`?`) for anything the code tolerates being unset.
/// <reference types="@meetploy/types/globals" />

declare module "@meetploy/nextjs" {
	interface PloyEnv {
		vars: {
			LLMGATEWAY_BASE_URL: string;
			RESEND_FROM_EMAIL: string;
			INBOUND_EMAIL_DOMAIN: string;
			BETTER_AUTH_URL: string;
			BETTER_AUTH_SECRET: string;
			DASHBOARD_URL: string;
			MARKETING_URL: string;
			SHOWCASE_URL: string;
			LLMGATEWAY_API_KEY: string;
			STRIPE_SECRET_KEY: string;
			STRIPE_WEBHOOK_SECRET: string;
			STRIPE_PRICE_STARTER?: string;
			STRIPE_PRICE_GROWTH?: string;
			STRIPE_PRICE_SCALE?: string;
			STRIPE_PRICE_STARTER_ANNUAL?: string;
			STRIPE_PRICE_GROWTH_ANNUAL?: string;
			STRIPE_PRICE_SCALE_ANNUAL?: string;
			STRIPE_PRICE_GROWTH_OVERAGE?: string;
			STRIPE_PRICE_SCALE_OVERAGE?: string;
			STRIPE_METER_EVENT?: string;
			INTERNAL_ACCOUNT_EMAILS?: string;
			// Comma-separated emails granted PLATFORM-admin access (the internal
			// admin dashboard). Bootstrap allowlist alongside the DB `user.role`.
			ADMIN_EMAILS?: string;
			// Canonical origin of the admin dashboard (admin.clankersupport.com),
			// used for /admin/* CORS + Better Auth trust. Optional: falls back to
			// http://localhost:3004 in dev.
			ADMIN_URL?: string;
			RESEND_API_KEY: string;
			RESEND_INBOUND_WEBHOOK_SECRET?: string;
			TRUSTED_CLIENT_IP_HEADER?: string;
			POSTHOG_API_KEY?: string;
			POSTHOG_HOST?: string;
			// Discord incoming-webhook URLs: operator notifications (signups,
			// subscription lifecycle) and the traffic report. Optional — all
			// notifications no-op when unset.
			DISCORD_NOTIFICATION_URL?: string;
			DISCORD_TRAFFIC_NOTIFICATION_URL?: string;
			// PostHog HogQL query credentials for the traffic-report cron: a
			// personal API key (phx_, read scope — NOT the phc_ ingestion key),
			// the numeric project id, and the app host (defaults to EU cloud).
			POSTHOG_PERSONAL_API_KEY?: string;
			POSTHOG_PROJECT_ID?: string;
			POSTHOG_QUERY_HOST?: string;
			// Weekly showcase-demo health probe (traffic-report cron): the PUBLIC
			// widget key the live showcase serves, and an optional override for the
			// API origin the probe calls (defaults to the prod origin). Unset ⇒
			// probe skipped (self-hosters / local dev).
			SHOWCASE_WIDGET_KEY?: string;
			API_PUBLIC_ORIGIN?: string;
			// Comma-separated project ids whose voice buckets are RAISED (not
			// removed) — dogfood relief scoped to named projects, never to the
			// internal workspace class (internal keys are published; audit
			// finding 5). Unset/empty ⇒ zero exemptions anywhere.
			VOICE_RAISED_LIMIT_PROJECTS?: string;
			GOOGLE_CLIENT_ID?: string;
			GOOGLE_CLIENT_SECRET?: string;
			GITHUB_CLIENT_ID?: string;
			GITHUB_CLIENT_SECRET?: string;
			// TRUSTED upstream base-URL overrides for integration clients (tests /
			// self-hosters / the demo mock). Server-set only — the untrusted stored
			// integration config no longer carries an apiBase (SSRF fix). Unset in
			// prod ⇒ Shopify is pinned to the shopDomain and Cal.com to api.cal.com.
			SHOPIFY_API_BASE?: string;
			CALCOM_API_BASE?: string;
		};
		DB: Database;
		STATE: StateBinding;
	}
}

declare global {
	interface PloyEnv {
		vars: {
			LLMGATEWAY_BASE_URL: string;
			RESEND_FROM_EMAIL: string;
			INBOUND_EMAIL_DOMAIN: string;
			BETTER_AUTH_URL: string;
			BETTER_AUTH_SECRET: string;
			DASHBOARD_URL: string;
			MARKETING_URL: string;
			SHOWCASE_URL: string;
			LLMGATEWAY_API_KEY: string;
			STRIPE_SECRET_KEY: string;
			STRIPE_WEBHOOK_SECRET: string;
			STRIPE_PRICE_STARTER?: string;
			STRIPE_PRICE_GROWTH?: string;
			STRIPE_PRICE_SCALE?: string;
			STRIPE_PRICE_STARTER_ANNUAL?: string;
			STRIPE_PRICE_GROWTH_ANNUAL?: string;
			STRIPE_PRICE_SCALE_ANNUAL?: string;
			STRIPE_PRICE_GROWTH_OVERAGE?: string;
			STRIPE_PRICE_SCALE_OVERAGE?: string;
			STRIPE_METER_EVENT?: string;
			INTERNAL_ACCOUNT_EMAILS?: string;
			// Comma-separated emails granted PLATFORM-admin access (the internal
			// admin dashboard). Bootstrap allowlist alongside the DB `user.role`.
			ADMIN_EMAILS?: string;
			// Canonical origin of the admin dashboard (admin.clankersupport.com),
			// used for /admin/* CORS + Better Auth trust. Optional: falls back to
			// http://localhost:3004 in dev.
			ADMIN_URL?: string;
			RESEND_API_KEY: string;
			RESEND_INBOUND_WEBHOOK_SECRET?: string;
			TRUSTED_CLIENT_IP_HEADER?: string;
			POSTHOG_API_KEY?: string;
			POSTHOG_HOST?: string;
			// Discord incoming-webhook URLs: operator notifications (signups,
			// subscription lifecycle) and the traffic report. Optional — all
			// notifications no-op when unset.
			DISCORD_NOTIFICATION_URL?: string;
			DISCORD_TRAFFIC_NOTIFICATION_URL?: string;
			// PostHog HogQL query credentials for the traffic-report cron: a
			// personal API key (phx_, read scope — NOT the phc_ ingestion key),
			// the numeric project id, and the app host (defaults to EU cloud).
			POSTHOG_PERSONAL_API_KEY?: string;
			POSTHOG_PROJECT_ID?: string;
			POSTHOG_QUERY_HOST?: string;
			// Weekly showcase-demo health probe (traffic-report cron): the PUBLIC
			// widget key the live showcase serves, and an optional override for the
			// API origin the probe calls (defaults to the prod origin). Unset ⇒
			// probe skipped (self-hosters / local dev).
			SHOWCASE_WIDGET_KEY?: string;
			API_PUBLIC_ORIGIN?: string;
			// Comma-separated project ids whose voice buckets are RAISED (not
			// removed) — dogfood relief scoped to named projects, never to the
			// internal workspace class (internal keys are published; audit
			// finding 5). Unset/empty ⇒ zero exemptions anywhere.
			VOICE_RAISED_LIMIT_PROJECTS?: string;
			GOOGLE_CLIENT_ID?: string;
			GOOGLE_CLIENT_SECRET?: string;
			GITHUB_CLIENT_ID?: string;
			GITHUB_CLIENT_SECRET?: string;
			// TRUSTED upstream base-URL overrides for integration clients (tests /
			// self-hosters / the demo mock). Server-set only — the untrusted stored
			// integration config no longer carries an apiBase (SSRF fix). Unset in
			// prod ⇒ Shopify is pinned to the shopDomain and Cal.com to api.cal.com.
			SHOPIFY_API_BASE?: string;
			CALCOM_API_BASE?: string;
		};
		DB: Database;
		STATE: StateBinding;
	}
}

export {};
