// This file is auto-generated by `ploy types`. Do not edit manually.
/// <reference types="@meetploy/types/globals" />

declare module "@meetploy/nextjs" {
	interface PloyEnv {
		vars: {
			LLMGATEWAY_BASE_URL: string;
			RESEND_FROM_EMAIL: string;
			INBOUND_EMAIL_DOMAIN: string;
			BETTER_AUTH_URL: string;
			BETTER_AUTH_SECRET: string;
			DASHBOARD_URL: string;
			MARKETING_URL: string;
			SHOWCASE_URL: string;
			LLMGATEWAY_API_KEY: string;
			STRIPE_SECRET_KEY: string;
			STRIPE_WEBHOOK_SECRET: string;
			STRIPE_PRICE_STARTER?: string;
			STRIPE_PRICE_GROWTH?: string;
			STRIPE_PRICE_SCALE?: string;
			STRIPE_PRICE_GROWTH_OVERAGE?: string;
			STRIPE_PRICE_SCALE_OVERAGE?: string;
			STRIPE_METER_EVENT?: string;
			INTERNAL_ACCOUNT_EMAILS?: string;
			RESEND_API_KEY: string;
			RESEND_INBOUND_WEBHOOK_SECRET?: string;
			POSTHOG_API_KEY?: string;
			POSTHOG_HOST?: string;
			GOOGLE_CLIENT_ID?: string;
			GOOGLE_CLIENT_SECRET?: string;
			GITHUB_CLIENT_ID?: string;
			GITHUB_CLIENT_SECRET?: string;
		};
		DB: Database;
		STATE: StateBinding;
	}
}

declare global {
	interface PloyEnv {
		vars: {
			LLMGATEWAY_BASE_URL: string;
			RESEND_FROM_EMAIL: string;
			INBOUND_EMAIL_DOMAIN: string;
			BETTER_AUTH_URL: string;
			BETTER_AUTH_SECRET: string;
			DASHBOARD_URL: string;
			MARKETING_URL: string;
			SHOWCASE_URL: string;
			LLMGATEWAY_API_KEY: string;
			STRIPE_SECRET_KEY: string;
			STRIPE_WEBHOOK_SECRET: string;
			STRIPE_PRICE_STARTER?: string;
			STRIPE_PRICE_GROWTH?: string;
			STRIPE_PRICE_SCALE?: string;
			STRIPE_PRICE_GROWTH_OVERAGE?: string;
			STRIPE_PRICE_SCALE_OVERAGE?: string;
			STRIPE_METER_EVENT?: string;
			INTERNAL_ACCOUNT_EMAILS?: string;
			RESEND_API_KEY: string;
			RESEND_INBOUND_WEBHOOK_SECRET?: string;
			POSTHOG_API_KEY?: string;
			POSTHOG_HOST?: string;
			GOOGLE_CLIENT_ID?: string;
			GOOGLE_CLIENT_SECRET?: string;
			GITHUB_CLIENT_ID?: string;
			GITHUB_CLIENT_SECRET?: string;
		};
		DB: Database;
		STATE: StateBinding;
	}
}

export {};
