// This file is auto-generated by `ploy types`. Do not edit manually.
/// <reference types="@meetploy/types/globals" />

declare module "@meetploy/nextjs" {
	interface PloyEnv {
		vars: {
			LLMGATEWAY_BASE_URL: string;
			RESEND_FROM_EMAIL: string;
			INBOUND_EMAIL_DOMAIN: string;
			BETTER_AUTH_URL: string;
			BETTER_AUTH_SECRET: string;
			DASHBOARD_URL: string;
			WIDGET_ALLOWED_ORIGINS: string;
			LLMGATEWAY_API_KEY: string;
			STRIPE_SECRET_KEY: string;
			STRIPE_WEBHOOK_SECRET: string;
			RESEND_API_KEY: string;
		};
		DB: Database;
		STATE: StateBinding;
	}
}

declare global {
	interface PloyEnv {
		vars: {
			LLMGATEWAY_BASE_URL: string;
			RESEND_FROM_EMAIL: string;
			INBOUND_EMAIL_DOMAIN: string;
			BETTER_AUTH_URL: string;
			BETTER_AUTH_SECRET: string;
			DASHBOARD_URL: string;
			WIDGET_ALLOWED_ORIGINS: string;
			LLMGATEWAY_API_KEY: string;
			STRIPE_SECRET_KEY: string;
			STRIPE_WEBHOOK_SECRET: string;
			RESEND_API_KEY: string;
		};
		DB: Database;
		STATE: StateBinding;
	}
}

export {};
